CREATE TABLE IF NOT EXISTS CLAIM (
   ID INT NOT NULL,
   CLAIM_DATE DATE NOT NULL,
   CLAIM_AMOUNT DOUBLE NOT NULL,
   MEMBER_ID INT
);

CREATE TABLE IF NOT EXISTS MEMBER (
   ID INT NOT NULL,
   ENROLLMENT_DATE DATE NOT NULL,
   FIRST_NAME VARCHAR(20) NOT NULL,
   LAST_NAME VARCHAR(20)
);
